### ISSUE TITLE
Weird thing about events

### ISSUE THREAD

**Issue by pagenoare** [smartystreets/jquery.liveaddress#12]
So, I've a pretty basic class initialization code:

```javascript
	var liveaddr = $.LiveAddress({
		key: 'MY_KEY',
		submitVerify: false,
		autoVerify: true,
		addresses: [{
			street: '#address1',
			city: '#city',
			zipcode: '#zip'
		}]
	});
```

And I'm trying to add custom handler on `AddressAccepted` event.

So, I've done this:
```javascript
    liveaddr.on("AddressAccepted", function(event, data, previousHandler) {
        debugger;
    });
```

I've opened a debug console on my chromium, started typing in #address1 field, choosen my address and nothing happened. As far as I know, after selecing correct address from autocomplete dropdown, my script should be stopped because of debugger thingy.

Am I doing something wrong?

BTW `MapInitialized`, `AddressChanged` and `AutocompleteReceived` events seem to work just fine. I've troubles with `AddressAccepted`, `Completed`, `AddressWasValid`.

Best Regards,
Kacper.

**Comment by camigreenall** [comment]
I know this may seem silly, but just to check are you entering an actual key in? Or do you keep `MY_KEY` there where you have your code. This would cause verification to fail and in turn cause `AddressAccepted`, `Completed`, and `AddressWasValid` to fail

**Comment by camiblanch** [comment]
@pagenoare I think I found the real solution. In your mapping you do not provide mapping to a `state` field.  The plugin cannot invoke verification because there is not enough data being provided. 

With your current setup you can invoke verification if you enter a zip code. Verification requires a `street` field and either a `city` + `state` combo or a `zipcode`

Let me know if that fixes your issue

**Comment by camiblanch** [comment]
I am going this due to inactivity. Let us know if you find this issue is still occurring.

**Comment by pagenoare** [comment]
Will do, sorry, I didnt get the chance to test that once again.

Will confirm it as fixed/still occuring when I get the time to take a look at this again.
