### ISSUE TITLE
Suggestion for documentation improvement regarding activate()

### ISSUE THREAD

**Issue by chico-borja** [smartystreets/jquery.liveaddress#14]
I think adding a sentence to your documentation for activate() to indicate that a deactivated address must have it's fields re-mapped before it can be used again would be helpful.  This only became clear to me after using debug mode and seeing the following message: 

Done cleaning up; ready for new mapping.

Thanks!

**Comment by camiblanch** [comment]
We are adding this in to the `deactivate` documentation on our website now. I will close this issue once it is live on the SmartyStreets website.

**Comment by camiblanch** [comment]
Added https://smartystreets.com/docs/plugin/functions#deactivate

**Comment by chico-borja** [comment]
Perfect, thanks!
