### ISSUE TITLE
Please register a Bower component

### ISSUE THREAD

**Issue by jhabdas** [smartystreets/jquery.liveaddress#15]
Thanks for open-sourcing this. People using it with Bower are currently required to do the following in their `bower.json` file to use this library:

`"jquery-liveaddress": "git@github.com:smartystreets/jquery.liveaddress.git#~2.4.11"`

It'd be nice if we could instead do:

`"jquery-liveaddress": "~2.4.11"`

http://bower.io/docs/creating-packages/

**Comment by mdwhatcott** [comment]
Forgive my being a total newbie to bower, but what's the advantage of the shorter, second line (other than being, well, shorter)?

**Comment by jhabdas** [comment]
It'll help ensure engineers use SemVer when including your lib as opposed
to omitting the version number and getting master. Additionally it'll make
your lib look more legit as well as gain you more community  exposure. It's
worth it.

**Comment by mdwhatcott** [comment]
Ok, thanks for the encouragement.

**Comment by camiblanch** [comment]
We recently published the plugin via npm if you are interested in that https://www.npmjs.com/package/liveaddress

**Comment by jhabdas** [comment]
Thanks. Bower seems to be on the way out so that works for me!
