### ISSUE TITLE
Modal window scrolling without smarty-ui div

### ISSUE THREAD

**Issue by blackbeersenator** [smartystreets/jquery.liveaddress#16]
I have a modal window which contains some text fields that work with smartystreets liveaddress plugin. The modal window goes outside the visible screen and is scrollable relative to main window which remains fixed in the background. 
Because smarty-ui tag is added to 'body' and not to modal window it remains in a fixed position when I scroll the modal. Is there any solution to overcome this kind of problem from js or css ?

**Comment by mdwhatcott** [comment]
I'm not sure if there's a clean workaround--you might have to fork the plugin code and make the edits that will allow it to be compatible with your design.

**Comment by mdwhatcott** [comment]
You might also go over the css documentation--something might strike you as a possible solution:

https://smartystreets.com/docs/plugin/css

**Comment by camiblanch** [comment]
We have an examples that show how to handle modal windows and such here:

[Bad Modal Usage](http://jsfiddle.net/pitcrew/snfa8zn7/) In this example you see how the smarty-ui stays visible even when the form is hidden

[Good Modal Usage](http://jsfiddle.net/pitcrew/v1vzb4eg/) In this example you see how by using the deactivate and activate functions the smarty-ui is hidden and shown according to the forms visibility
