### ISSUE TITLE
Prevent Form Submission On Selecting "certify the address is correct"

### ISSUE THREAD

**Issue by RoLYroLLs** [smartystreets/jquery.liveaddress#17]
We have a form which asks the user for various pieces of information. The address is located on the top section. As I was testing this plugin to see what happens when someone enters an address that has no suggestions and chooses to "certify the address is correct" (I'll call it "certify")I noticed the form gets's submitted.

When someone clicks certify, the following events are triggered, as shown when debug = true: "Completed", "OriginalInputSelected", "AddressAccepted", and "Completed".

Looking through the source I noticed the submission happens at line 2502, after event "AddressAccepted" is triggered.

Maybe I missed this somewhere, but what is the best way to make sure the plugin does not submit the form when certifying an address? If there is no way, can this be added?

Here's what I came up with after looking through some of the customizations, however I am currently testing this to make sure it works:
```javascript
liveaddress.on('AddressAccepted', function (event, data, previousHandler) {
    data.invokeFn = null;
    previousHandler(event, data);
});
```

UPDATE
------------
After testing above, I found that "AddressAccepted" gets called on other instances and the form would not submit when it needed to. I updated and tested the code above to:
```javascript
liveaddress.on('OriginalInputSelected', function (event, data, previousHandler) {
    data.invokeFn = null;
    previousHandler(event, data);
});
```

If I'm doing something wrong, please feel free to correct me.

**Comment by camiblanch** [comment]
@RoLYroLLs The plugin only submits the form when you click "certify the address is correct" if verification was invoked from clicking the submit button in the first place. If you invoke verification by clicking on the checkmark, or it is done automatically, then clicking "certify the address is correct" will not submit the form.

**Comment by camiblanch** [comment]
I am going this due to inactivity. Let us know if you find this issue is still occurring.
