### ISSUE TITLE
Lookup doesn't pull zipcode like your the examples page does

### ISSUE THREAD

**Issue by codymorgan** [smartystreets/jquery.liveaddress#19]
I couldn't find any documentation to address my question, but here is the rub:

the examples shown at https://smartystreets.com/docs/plugin/examples behave differently in regards to zipcodes than when i implement the same javascript on my site.

although the debug shows the zipcode field mapped appropriately, it doesn't get populated as things do in your examples

here's my code
http://jsfiddle.net/sn4bskLj/4/

**Comment by mdwhatcott** [comment]
@codymorgan - You'll need to add a State text field to your form. That will allow the response to be verified from an autocomplete selection.

**Comment by codymorgan** [comment]
awesome thanks!
