### ISSUE TITLE
Bind to Hidden elements

### ISSUE THREAD

**Issue by yagyesh11235** [smartystreets/jquery.liveaddress#23]
I've noticed the plugin doesn't bind itself to hidden form fields, even if it's explicitly mentioned when initializing.

```html
<form id="happyPath1" style="display:none">
		<header>
			<h3>Happy path</h3>
			<p>The simplest, most traditional kind of address form</p>
		</header>
		<table>
			<tr>
				<td>Street address:</td>
				<td><input type="text" name="street"></td>
			</tr>
			<tr>
				<td>City:</td>
				<td><input type="text" name="city"></td>
			</tr>
			<tr>
				<td>State:</td>
				<td><input type="text" name="state"></td>
			</tr>
			<tr>
				<td>ZIP Code:</td>
				<td><input type="text" name="zip"></td>
			</tr>
			<tr>
				<td></td>
				<td><input type="submit" value="Submit Form"></td>
			</tr>
		</table>
	</form>
```
add this block to index.html.

Now open the index.html using firebug now remove display none so our hidden form is displayed now
![image](https://cloud.githubusercontent.com/assets/3796564/7386021/957b4748-ee6c-11e4-84da-3f095466e21c.png)

Here we can see now there is no suggestion loading

Any thoughts?

**Comment by yagyesh11235** [comment]
closing this as they may be related to https://github.com/smartystreets/jquery.liveaddress/issues/24

**Comment by camigreenall** [comment]
After you remove the styling you have to call liveaddress.mapFields() to initialize remapping. We don't support mapping/validation on hidden forms and there is nothing listening to see if the form is no longer hidden.
