### ISSUE TITLE
Binding Multiple Forms

### ISSUE THREAD

**Issue by yagyesh11235** [smartystreets/jquery.liveaddress#24]
Can we bind different form individually.

```js
	$("#happyPath").LiveAddress({
             key: "yourKey",
             token:"token",
             debug: true //Show debug stuff
       });	

   $("#street2").LiveAddress({
              key: "yourKey",
             token:"token",
             debug: true //Show debug stuff
       });	
```
In above case binding only happens for ``` happypath``` form not for  ```street2```

Any thoughts??

**Comment by yagyesh11235** [comment]
According to documentation 

"The SmartyStreets website plugin is configured when it is initialized. Initialization occurs when jQuery.LiveAddress() is called. The plugin must be initialized before it can be used, and it should only be initialized once."

so closing this issue

**Comment by yagyesh11235** [comment]
1) http://jsfiddle.net/uhhsefz2/
2) http://jsfiddle.net/hz8tLLk4/

**Comment by camiblanch** [comment]
We don't plan on adding support for binding to hidden forms, but we do plan on adding support to bind to multiple forms as seen in your original request. This won't be available for a while as it is going to be added in with our rewrite of the plugin in a major version

**Comment by camiblanch** [comment]
Unfortunately, we, SmartyStreets, have decided to scrap this enhancement. We encourage you to fork out your own copy and add in this feature if you would like it.
