### ISSUE TITLE
Too Aggressive Loaded Strategy?

### ISSUE THREAD

**Issue by metaskills** [smartystreets/jquery.liveaddress#28]
Today I noticed that an image was not loading in our checkout cart and that caused the SmartyStreets jQuery plugin to not work. The issue seems to be that this plugin uses `document.readyState === "complete"` to set `window.loaded = true`. Is this too aggressive? Why not use jQuery ready handler?

The comments in the plugin code state "document be fully loaded in order to attach UI elements" and using jQuery's ready should allow that too? Could something like the following change work?

``` diff
- window.loaded ? ui.postMappingOperations() : $(window).load(ui.postMappingOperations);
+ window.loaded ? ui.postMappingOperations() : $(ui.postMappingOperations);
```

Here are a few resources. Both seem to be me that using either `interactive` or just letting jQuery's ready do the work for us are better. Thoughts?
- jQuery ready API - https://api.jquery.com/ready/
- Document.readyState API - https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState

**Comment by metaskills** [comment]
When using debug mode, I can see this event.

```
EVENT: FieldsMapped (Fields mapped to their respective addresses)
```

But it takes a few minutes before the image load fails and hence never makes it to this even and other.

```
EVENT: MapInitialized (Mapped fields have been wired up to the window, document, and UI)
```

**Comment by camiblanch** [comment]
@metaskills Are you stilling having issues with this being too aggressive?

**Comment by metaskills** [comment]
I honestly do not know since I have not been actively developing the part of our site that uses this plugin. I would suspect that unless something has changed about the implementation since this issue was created, it would still be true.

cc @h-m-m

**Comment by camiblanch** [comment]
Would a good solution be to update that line (now line 149) to 
`window.loaded ? ui.postMappingOperations() : $(window).on("ready", ui.postMappingOperations);`

**Comment by metaskills** [comment]
Yes, I believe that is the exact same as this?

```javascript
window.loaded ? ui.postMappingOperations() : $(ui.postMappingOperations)
```

**Comment by camiblanch** [comment]
Yes that's correct. That would probably be better since it's more concise. I'll go ahead and make that update
