### ISSUE TITLE
Latest v2.8.8 - ERROR: Not an array or string passed in to undelegate all clicks

### ISSUE THREAD

**Issue by metaskills** [smartystreets/jquery.liveaddress#29]
When doing things like choosing a candidate, or closing the list. I see this error alert. The object passed looks something like this.

```
Object
  abort: ".smarty-popup.smarty-addr-shipping .smarty-abort"
  goodAddr: ".smarty-popup.smarty-addr-shipping .smarty-choice-list .smarty-choice"
  useOriginal: ".smarty-popup.smarty-addr-shipping .smarty-choice-override"
```

**Comment by metaskills** [comment]
Seems this error started in v2.8.7 

![screen shot 2015-09-14 at 4 51 27 pm](https://cloud.githubusercontent.com/assets/2381/9861545/f38062fa-5b00-11e5-978d-00e7b4a775e1.png)

**Comment by metaskills** [comment]
Commit is 5a5f92a2

**Comment by camiblanch** [comment]
I understand. This bug comes up when an ambiguous address is selected. Otherwise, it works correclty

**Comment by metaskills** [comment]
I've made some hacks in my local copy to pass down `abort`, `goodAddr`, etc in the functions that call  `undelegateAllClicks`... but I took guesses. So I look forward to when this is fixed.

**Comment by camiblanch** [comment]
Should be working smoothly now. 2.8.9 is published and ready to go

**Comment by metaskills** [comment]
Thanks for the quick turn-a-round. Might I suggest that y'all have some integration tests to catch these too :) Either way, I appreciate the OS and your work on this.
