### ISSUE TITLE
IE9 $.ajax and using dataType: "jsonp"

### ISSUE THREAD

**Issue by metaskills** [smartystreets/jquery.liveaddress#30]
I noticed that this commit 9cec9545 removed the JSONP datatype and this made IE9 not work anymore. I added that back in and everything seems to work fine. Any reason that should not be in by default?

**Comment by camiblanch** [comment]
When I made that commit I remember there being some issues with having the JSONP dataType. Now I can't seem to get that error anymore. Fix will be pushed soon

**Comment by camiblanch** [comment]
Pushed out as version 2.8.10. Let me know if there are still issues concerning this bug
