### ISSUE TITLE
Alert Error Shown To User With Pressing ESC

### ISSUE THREAD

**Issue by mattbegent** [smartystreets/jquery.liveaddress#33]
An alert with the error message "ERROR: Not an array, string, or object passed in to undelegate all clicks" is displayed when a user presses ESC when the "Address Not Verified" popup displays. Please can this be fixed.

Steps to reproduce:

1. Visit [https://smartystreets.com/docs/plugin](https://smartystreets.com/docs/plugin) and type in an unverified address e.g. 12333 County Road 3

2. When the "Address Not Verified" popup displays press ESC.

3. The alert error will display.

It should close the popup instead of showing an error message.

**Comment by camiblanch** [comment]
Fix is published in version 2.8.27
Thanks for catching this bug.
