### ISSUE TITLE
Previous binding not being cleared

### ISSUE THREAD

**Issue by rauanmaemirov** [smartystreets/jquery.liveaddress#38]
In this line: https://github.com/smartystreets/jquery.liveaddress/blob/master/src/jquery.liveaddress.js#L467

When you reinitialise liveaddress, `$(document).unbind(prop, HandleEvent);` doesn't clear previous event handlers. 

This behaviour can be reproduced on Chrome 50.0.2661.94 by initialising and then deactivating plugin several times. Then, while using autosuggest, event handlers will be triggered several times. (`$(document).unbind(prop);` solved the issue for me)

**Comment by camiblanch** [comment]
Could you provide me the exact commands you are running to deactivate and then instantiate the plugin? I am having trouble replicating this.

**Comment by camiblanch** [comment]
@rauanmaemirov If I don't hear back from you within 3 days, I will close this card.

**Comment by rauanmaemirov** [comment]
Sorry about that. A little busy these days, will get back to that later.
