### ISSUE TITLE
Getting Uncaught Exception with International address response

### ISSUE THREAD

**Issue by tjohar** [smartystreets/jquery.liveaddress#40]
I'm getting below errors from `jquery.liveaddress.js` file with my international address response. [International address response](https://smartystreets.com/docs/international-street-api#http-response-status) does not have `analysis.dpv_footnotes`, hence why I'm getting below error. 

<img width="844" alt="screen shot 2016-06-15 at 9 32 20 pm" src="https://cloud.githubusercontent.com/assets/10803354/16081611/d75e3d86-3340-11e6-94ac-667f604691fc.png">

I'm not sure whether it is a bug or misconfiguration. Below is my configuration for my international address fields.

```ruby
  var options = {
    key: "<%= ENV['SMARTY_STREET_KEY'] %>",
    debug: false,
    autocomplete: 0,
    target: "International",
    missingSecondaryMessage: "Missing secondary number(e.g., apartment number)",
    addresses: [
      {
        address1: "#address_1",
        address2: "#address_2",
        locality: "#city",
        administrative_area: "#region",
        postal_code: "#postal_code",
        country: "#country"
      }
    ]
  };

  $.LiveAddress(options);
```

Appreciate for any pointers. Thanks.

**Comment by camiblanch** [comment]
Let me know if you're still seeing this bug and I'll open the issue again. Should be fixed now!
