### ISSUE TITLE
Load NPM package

### ISSUE THREAD

**Issue by yankeyhotel** [smartystreets/jquery.liveaddress#41]
What's the best way to load the NPM package into React?

`import LiveAddress from 'liveaddress.min.js';` throws the following error in our Meteor app.

`Error: Can't find npm module 'liveaddress'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?`

**Comment by camiblanch** [comment]
I'm not super familiar with Meteor or React, but I found [this documentation](http://guide.meteor.com/using-npm-packages.html#installing-npm) that you might find helpful.

1. [Make sure you have npm installed](https://docs.npmjs.com/getting-started/installing-node)
2. Install the liveaddress npm package via Meteor and npm
`meteor npm install --save liveaddress`
3. Import the package into your Meteor app
`import LiveAddress from 'liveaddress';`

Let me know if that eliminates the errors in your code

**Comment by yankeyhotel** [comment]
If I add a `main` key to `package.json` I can get the module to load. My understanding is it just needs to know which file to load in.

```
...
"main": "src/jquery.liveaddress.js"
...
```

But now I am getting an error about jQuery not being defined.
`ReferenceError: jQuery is not defined`

Any ideas? Thanks.

**Comment by camiblanch** [comment]
I will add the "main": "src/jquery.liveaddress.js" to the package.json file
