### ISSUE TITLE
Unsanitized input in Regex causes js errors

### ISSUE THREAD

**Issue by brainded** [smartystreets/jquery.liveaddress#42]
If you use a "(" or ")" in the address field it causes JS errors because there is a regex being used to find and replace that is using unsanitized or unconverted input. The line the issue exists in is here:
https://github.com/smartystreets/jquery.liveaddress/blob/master/src/jquery.liveaddress.js#L937

The error in the console is as follows:
Uncaught SyntaxError: Invalid regular expression: /(12348 ()/: Unterminated group

**Comment by camiblanch** [comment]
Could you give me an exact example of the input you are using to get this error?

**Comment by brainded** [comment]
Sure! In Address 1 I typed "1234 Nowhere (Apt 2)". As soon as I hit the "(" key it causes the JS exceptions.

**Comment by camiblanch** [comment]
Awesome thanks! I'll get working on a fix

**Comment by camiblanch** [comment]
You should see the fix in version 3.1.10 of the plugin. Just pushed to publishing to our cloud server.

**Comment by brainded** [comment]
Awesome! Thanks for the quick turnaround!
