### ISSUE TITLE
Another Uncaught TypeError

### ISSUE THREAD

**Issue by tamarazuk** [smartystreets/jquery.liveaddress#46]
Hey again, I'm running into a similar TypeError as #45, this time on [this line](https://github.com/smartystreets/jquery.liveaddress/blob/3d8897c1a9107b5c0ff25112495b78c6d05300b4/src/jquery.liveaddress.js#L2403). Changing the line above to something like the following fixes it for me:

```
if (fields[key].dom && fields[key].dom.tagName === "SELECT" && fields[key].dom[fields[key].dom.selectedIndex]) {
```

I would love it if the whole library could be inspected for instances such as these when you guys have a moment so errors like these can be avoided :) Thanks!

**Comment by camiblanch** [comment]
I think I was able to isolate the problem. This bug happens when the plugin detects a state dropdown, but the `selectedIndex` is set to an item that doesn't exist in the dropdown. This causes `selectedIndex` to be equal to `-1`. The workaround is to default to an empty string value in this case. 

The fix would also apply to the country field if it is a dropdown and `selectedIndex` is set to `-1`.

**Comment by camiblanch** [comment]
If that sounds like it will still work out for you, I will go ahead and publish the change. Please let me know what your thoughts are @tamarazuk

**Comment by tamarazuk** [comment]
@camiblanch I can give the fix a try locally once you push it. Thanks for looking into it :)

**Comment by camiblanch** [comment]
Here is a branch that has the fixes I described. https://github.com/smartystreets/jquery.liveaddress/tree/dropdown-out-of-index-bandaid

Download it and let me know how it works

**Comment by tamarazuk** [comment]
thanks @camiblanch, so far it looks like this fix is working well for me, but I will open up a new issue if I run into errors again. Thanks!

**Comment by camiblanch** [comment]
Okay sounds great! I will merge that branch into the master branch since it provides improvement to the plugin.

**Comment by camiblanch** [comment]
Merged
