### ISSUE TITLE
FieldsMapped & MapInitialized race condition?

### ISSUE THREAD

**Issue by ragulka** [smartystreets/jquery.liveaddress#48]
Given the following code:
```javascript

liveaddress = $.LiveAddress( options );
liveaddress.on( 'FieldsMapped', function() {
  console.log('Fields are mapped!');
}); 
liveaddress.on( 'MapInitialized', function() {
  console.log('Map is initalized!');
}); 
```
The messages are never logged to the console. When switching debug mode on, I can see that the MapInitalized event is internally called before the liveaddress instance is returned.

**Comment by camiblanch** [comment]
Yes that is true. The liveaddress instance is not returned before you setup those event handlers. You would either have to use jQuery's built in event handler like so
```
$(window).on( 'FieldsMapped', function() {
  console.log('Fields are mapped!');
}); 
$(window).on( 'MapInitialized', function() {
  console.log('Map is initalized!');
}); 
```

or setup some kind of delay before calling `liveaddress.on(...)`

It may seem weird that these events are available, but are hard to reach. A more common usage is to watch on those specific events to know when a remapping occurs.

Also, when using the LiveAddress `.on()` function to handle events, make sure you include a callback to the previous event handler. You can see an example of this [here](https://smartystreets.com/docs/plugins/website/events). This will insure that the functionality for that event that is handled by the plugin still runs.

Does that help answer your question?

**Comment by camiblanch** [comment]
@ragulka Closing this issue if I don't hear back from you by Monday

**Comment by camiblanch** [comment]
Closing due to no response.
