### ISSUE TITLE
verifySecondary example and code broken

### ISSUE THREAD

**Issue by perplexes** [smartystreets/jquery.liveaddress#49]
I can't get verifySecondary to work correctly.

In the example: https://jsfiddle.net/smartystreets/untutr1p/

Try entering a suite number when the dialog pops up, after entering the example address: 3214 N University Ave Provo UT

Any input makes the modal dialog pop back up, even a valid suite number.

Here's my example from a real address:
15251 SIESTA KEY WAY
ROCKVILLE, MD

Valid apt# is 496.

The popup keeps appearing, no matter the input.

From the http traffic it looks like the entered secondary isn't making it to the api call perhaps?

Thank you!

**Comment by camiblanch** [comment]
@perplexes Which browser are you using? I tested this in Chrome, Firefox, and Safari and it seems to be working fine

**Comment by camiblanch** [comment]
Another question: What exactly are you entering in to the pop up dialog? Just "409" or "suite 409"?

**Comment by perplexes** [comment]
I was entering APT 496 or STE 409, looks like you have to enter the number only? I feel like that's not in the documentation or expected behavior. Thoughts?

**Comment by camiblanch** [comment]
Good point. We'll start working on a better way to display to the user that the secondary number was submitted to the api, but was invalid still.

**Comment by perplexes** [comment]
Thank you! I think even just giving an example/placeholder in the box would help a bunch.

**Comment by camiblanch** [comment]
After thinking about it, how would it be if the placeholder text was changed to "Enter number here" and the message text above it was changed to "You forgot your apt/suite number or entered an invalid suite number"?

**Comment by camiblanch** [comment]
@perplexes Still waiting on an answer to my previous question
