### ISSUE TITLE
submitVerify is stopping Firefox from continuing the form submit

### ISSUE THREAD

**Issue by ShaunaGordon** [smartystreets/jquery.liveaddress#5]
When I have submitVerify on a form with separate address fields, LiveAddress runs the validation and completes the address (if possible), but then stops the form from continuing its submission, even on valid addresses. This only happens in Firefox. The form resumes normal behavior when submitVerify is set to false. 

Debug mode shows "AddressWasValid," "AddressAccepted" and "Completed" event messages, indicating that it should continue on and complete the form submission.

**Comment by camiblanch** [comment]
@ShaunaGordon I found that changing the event listener to 
    `$('[type="submit"]').click(function (event) {
        alert('Submitted!');
        event.preventDefault();
    });`
works in both Firefox and Chrome.

**Comment by metaskills** [comment]
I am now seeing this issue too. We recently updated our site to mobile/responsive and this just turned up out of nowhere. We were at v2.4.11and I just tried with 2.8.5 too, no avail.

**Comment by camiblanch** [comment]
@metaskills Could you send me the link to the site that you are seeing this behavior? I'm having trouble replicating this bug myself.

**Comment by metaskills** [comment]
You will need to go in the lab and make a quick shirt.

http://www.customink.com/checkout/shipping

I will likely be doing a hot deploy here in a few minutes and disable LA for firefox.

**Comment by camiblanch** [comment]
@metaskills Ok I was able to replicate the issue in a jsFiddle. I will be looking into this issue this week

**Comment by metaskills** [comment]
@camiblanch Thanks so much! It would be great if we could turn on FireFox again.

**Comment by metaskills** [comment]
Wonder if this is related. Request finished but Firefox says it is still transfering.

![screen shot 2015-08-25 at 10 36 26 am](https://cloud.githubusercontent.com/assets/2381/9469477/3a09f070-4b15-11e5-9df3-d2054aac19ef.png)

**Comment by camiblanch** [comment]
@metaskills Let me know if you still see the issue in the latest version (2.8.6) of the plugin.

**Comment by metaskills** [comment]
Can we re-open this issue? The commit did not resolve FF for me. Same behavior still exists.

**Comment by camiblanch** [comment]
Issue is back

**Comment by camiblanch** [comment]
Further investigation shows that the previous fix only works if you step through the code or throw in a breakpoint.

**Comment by camiblanch** [comment]
Just pushed this out as version 2.8.8 

Should work now. I tested without stepping through or using breakpoints and was able to get the form to submit correctly

**Comment by metaskills** [comment]
Thanks! Think I am getting someplace... but #29 is now blocking me.
