### ISSUE TITLE
Autocomplete Problematic Address

### ISSUE THREAD

**Issue by ryanjerskine** [smartystreets/jquery.liveaddress#51]
I'm using your autocomplete API and I noticed that the following
3896 Highwa
populated with the correct suggestions. However as soon as I added the 'y':
3896 Highway
The suggestions don't really make sense:
3896 HC 1, Agat GU
3896 HC 0, Chelan WA
etc..

**Comment by camiblanch** [comment]
That is some strange behavior... We will look into this and get back to you.

**Comment by MouaYing** [comment]
This has been fixed, and will be in effect in the next release of our US Autocomplete API.
