### ISSUE TITLE
Improve UI markup + CSS conventions

### ISSUE THREAD

**Issue by rafegoldberg** [smartystreets/jquery.liveaddress#53]
You guys got address validation down– the `$.LiveAddress` function makes it really simple to set up and use. On the other hand, styling the plugin is a mess, forcing devs to write hacky selectors and use `!important` overrides. I'd urge you reconsider this approach and _radically_ simplify your default CSS and markup for the `.smarty-ui` components. At the moment, styling the UI layer requires devs to write horrendous CSS.

**Comment by rafegoldberg** [comment]
From the docs:

> Since the plugin is designed to survive in some hostile web page environments, it was necessary for us to force certain rules to preserve usability. If you experience difficulty getting your style rules to override some of our defaults, try using the !important declaration.

May the lord have mercy on us all!

**Comment by camiblanch** [comment]
We will look into improving this. I like the idea of simplifying the CSS. The first step will probably be to extract the CSS into it's own file so it can be managed more efficiently

**Comment by camiblanch** [comment]
This commit https://github.com/smartystreets/jquery.liveaddress/commit/a4ea3c7d8c13ea7043b1cc956100af77a0a1b3b1 eliminated `!important` in the css. Still working on getting the css moved out into it's own file.

**Comment by cbuchert** [comment]
@rafegoldberg I'm working on a branch to refactor the styling in the plugin. You can find the branch [here](https://github.com/smartystreets/jquery.liveaddress/tree/chris/simplify-styling). Currently, I've extracted all styling into an external style sheet and updated all selectors to be `class` only (no more `id`s! Yay!) Things I'm still interested in doing in this branch are further simplifying the selectors and updating the styling to be mobile-friendly out of the box. I'd love your feedback.

**Comment by rafegoldberg** [comment]
Hey @cbuchert; sounds great. I’ll take a look when I have a moment.

**Comment by rafegoldberg** [comment]
@cbuchert getting back to this today. glanced briefly at your SCSS, which looks _far_ improved already. will let you know when I've had a chance to look in a bit more depth!

**Comment by cbuchert** [comment]
@rafegoldberg Wow, it's been a year.

We've been waffling on this for a year, unwilling to commit to requiring a second file for users looking for drop-in functionality. Last week I took the leap and broke the plugin apart into declaration and invocation which has opened up a world of possibilities for improvements like this. I have a branch that we'll be reviewing for commit that will make this official (at last). You can find the new branch [here](https://github.com/smartystreets/jquery.liveaddress/tree/chris/separate-styling).

**Comment by cbuchert** [comment]
This plugin has been deprecated, so there will be no continued development on the project. If you're looking for a more flexible JavaScript solution for integration with SmartyStreets APIs, check out the [SmartyStreets JavaScript SDK](https://github.com/smartystreets/smartystreets-javascript-sdk).
