### ISSUE TITLE
Unexpected or empty field value properties when fields controlled by Angular

### ISSUE THREAD

**Issue by lishs** [smartystreets/jquery.liveaddress#56]
I'm currently Integrating liveaddress with an ecommerce platform allowing checkout plugins, one of which uses angular.  This confuses liveaddress's field values.

I've created a fix here: https://github.com/lishs/jquery.liveaddress

Great plugin!

**Comment by lishs** [comment]
Also, not to nitpick semantics, but jquery and this liveaddress plugin are libraries, not frameworks.

**Comment by camiblanch** [comment]
Sounds great! Glad you were able to find a fix!

**Comment by mdwhatcott** [comment]
@lishs 2c969282d6dfb799526da78edab7fb2cd4863eed
