### ISSUE TITLE
Input Placeholders

### ISSUE THREAD

**Issue by dja** [smartystreets/jquery.liveaddress#62]
Is there any way to use this without displaying/overriding the placeholder text in inputs?

**Comment by dja** [comment]
Nevermind - realized it was due to `debug: true`. I couldn't find the answer to this in the documentation though..

**Comment by dMcCaffree** [comment]
That information can be found [on our docs for the website plugin, under "configure."](https://smartystreets.com/docs/plugins/website/configure), as seen in the attached screenshot of that page.

Thank you for closing this issue! We look forward to hearing more from you in the future.

<img width="1211" alt="screenshot 2017-11-13 09 49 28" src="https://user-images.githubusercontent.com/14884927/32737826-5b72a474-c858-11e7-920b-a91dd77d3e31.png">
