### ISSUE TITLE
postal_code does not trigger change event

### ISSUE THREAD

**Issue by billheaton-q2** [smartystreets/jquery.liveaddress#63]
For some reason the `doSet` method is called with `keepState` as `true` when the `postal_code` is set via the US API response.

**Expected behavior:**

At some point when the response has a valid address the keepState should be false so that `AddressChanged` is triggered. Also the dom input element should fire `change` when the `postal_code` is set. 

**Actual behavior:**

In the `replaceWith` method at https://github.com/smartystreets/jquery.liveaddress/blob/master/src/jquery.liveaddress.js#L2138 the `keepState` is hard coded as `true`. 

The effect is that our application code is not aware that the postal code has changed so we are not able to persist the data.

**Steps to reproduce:**

- Setup Smartystreets Website plugin with a single address.
- In separate application code add a listener for the 'change' event on a postal_code input element. Add a debugger in the event handler to inspect the event.  It should be fired when a postal_code is updated via the US API response.
- Also add an listener to the plugin event `AddressChanged`, and inspect the event. It should be fired when a postal_code is updated via the US API response.

**Workaround:**

```javascript
plugin.on('AddressAccepted', (event, data, previousHandler) => {
  previousHandler(event, data);
  let el = data.address.getDomFields().postal_code;
  let evt = document.createEvent('HTMLEvents');
  evt.initEvent('change', true, false);
  el.dispatchEvent(evt);
});
```

**Comment by cbuchert** [comment]
This plugin has been deprecated, so there will be no continued development on the project. If you're looking for a more flexible JavaScript solution for integration with SmartyStreets APIs, check out the [SmartyStreets JavaScript SDK](https://github.com/smartystreets/smartystreets-javascript-sdk).
