### ISSUE TITLE
Verify > Undo > Verify = You Didn't Enter Enough Information

### ISSUE THREAD

**Issue by bas-tyler** [smartystreets/jquery.liveaddress#64]
I've verified an address, and then selected to Undo the verification. Without manually making any changes I tried to verify again and was met with "YOU DIDN'T ENTER ENOUGH INFORMATION" error dialog.
With my implementation, this only happens when _country_ is left out from the LiveAddress definition.

```
var liveAddress = $.LiveAddress({
	            key: 'MY_KEY',
	            debug: true,
	            target: "US",
                waitForStreet: true,
                autoVerify : false,
	            addresses: [{
		            address1: '[id*="billingStreet"]',
		            locality: '[id*="billingCity"]',
		            administrative_area: '[id*="billingState"]',
		            //country: '[id*="billingCountry"]',
		            postal_code: '[id*="billingPostalCode"]'
	            },{
		            address1: '[id*="shippingStreet"]',
		            locality: '[id*="shippingCity"]',
		            administrative_area: '[id*="shippingState"]',
		            //country: '[id*="shippingCountry"]',
		            postal_code: '[id*="shippingPostalCode"]'
	            }]
            });
```

Once I remove the commented attribute, the same steps above do not product the error.

Tracing the debug logs, I see that the Undo is "changing" the address by setting the country to an empty string.

`EVENT: AddressChanged (Address changed) n.Event {type: "AddressChanged", timeStamp: 1516392464555, jQuery22005615625696223798: true, isTrigger: 2, namespace: "", …} {sourceEvent: undefined, field: "country", address: w, value: "", suppressAutoVerification: true}`

**Comment by camiblanch** [comment]
I was able to replicate this error. I will fix this as soon as possible. If you find a solution sooner than I am able to you are more than welcome to create a pull request.

**Comment by camiblanch** [comment]
Just released the patch for this. Let me know if you're still having issues!
