### ISSUE TITLE
Issue in International address varification

### ISSUE THREAD

**Issue by ajayhada** [smartystreets/jquery.liveaddress#65]
Plugin version 3.1 and Demo page https://smartystreets.com/products/single-address  apis mark address as valid/verified but plugin version 5.1.1 mark same address as invalid. 

see screenshots. 

the first screenshot is from the demo page and it simply shows address as verified(I am not sure about the version used on demo page but I tried same address with v3.1 and it worked.) but when i try to verify same address using version5.1.1 it opens a popup with message "You entered an unknown address. "

![screenshot from 2018-01-25 19-05-23](https://user-images.githubusercontent.com/1167461/35391141-ca030476-0203-11e8-8e05-f89f3ed4a5e4.png)

![5 1 1address verification](https://user-images.githubusercontent.com/1167461/35391122-bb8814cc-0203-11e8-9619-8c8bc5eafab4.png)

**Comment by camiblanch** [comment]
Good catch! In both of these cases they are getting the same data back from the API, specifically the `analysis` component. The only difference is how that data is interpreted. 

In the Single Address Demo it sees `analysis.verification_status: "Verified"` and displays _Found **1** valid address_. 

In the jQuery plugin it sees `analysis.address_precision: "Locality"` which is then interpreted as and invalid address. ([reference](https://github.com/smartystreets/jquery.liveaddress/blob/master/src/jquery.liveaddress.js#L2715))

Ideally, what would you expect to see changed to solve your issue?

**Comment by ajayhada** [comment]
I guess it should be consistent. so version 5.1.1 should show "Address was verified down to the locality" instead "You entered an unknown address".
1. if the address is unknown or not verified then it should open a popup with message "You entered an unknown address".
1. if the address is verified at any precision level then it should show  "Address was verified down to the XXXXX level." in popup.
1. if the address is verified then then no change.

**Comment by jwnacnud** [comment]
@ajayhada What would you like to see if the only thing that can be validated is the country?

**Comment by cbuchert** [comment]
This plugin has been deprecated, so there will be no continued development on the project. If you're looking for a more flexible JavaScript solution for integration with SmartyStreets APIs, check out the [SmartyStreets JavaScript SDK](https://github.com/smartystreets/smartystreets-javascript-sdk).
