### ISSUE TITLE
Response Fail Issue

### ISSUE THREAD

**Issue by alisoofeeaan** [smartystreets/jquery.liveaddress#66]
**Cannot read property 'split' of undefined**

Some time response fails and stuck the code.

I have fix this with this example.

var ad = ac.responseText;
if (typeof(ad) === 'undefined')
{
	ad = 0;
}else
{
	ad = ac.responseText.split("\n")[0].indexOf("country");
}

**Comment by camiblanch** [comment]
I'm not understanding what the problem is exactly. Could you reproduce this error using the unminified version of the plugin code `d79i1fxsrar4t.cloudfront.net/jquery.liveaddress/5.1/jquery.liveaddress.js`? Let me know what line number you are seeing the error.

**Comment by alisoofeeaan** [comment]
line no 2375.
unknown reason response goes to fail some time "xhr.responseText" is undefined therefor break my script.

**Comment by camiblanch** [comment]
Should be working for you now. Thanks for finding that bug.
