### ISSUE TITLE
Having a pre filled form + autoVerify: true config setting results in the wrong address being verified

### ISSUE THREAD

**Issue by eveshumwork** [smartystreets/jquery.liveaddress#67]
Hi!

jfiddle: https://jsfiddle.net/y6w8b399/813/

If you have a pre filled form, and you edit the address via autocomplete functionality, then the wrong address will be sent for verification, which results in an error message saying a valid address is invalid.

**How to reproduce**

1. have a form with pre filled inputs. Do not hit the verify button.
<img width="218" alt="screen shot 2018-03-15 at 3 41 11 pm" src="https://user-images.githubusercontent.com/12614345/37494709-4f8680d0-2867-11e8-8c1f-97819c2acc76.png">

2. Type in a new address (valid)
<img width="304" alt="screen shot 2018-03-15 at 3 41 45 pm" src="https://user-images.githubusercontent.com/12614345/37494728-65a5125a-2867-11e8-8386-956dab4948f7.png">

3. Select the valid address. Notice that the address is "invalid"
<img width="440" alt="screen shot 2018-03-15 at 3 42 28 pm" src="https://user-images.githubusercontent.com/12614345/37494749-7d84cc12-2867-11e8-888e-ed66dd79f18a.png">

4. Click "go back" and click "verify" again
<img width="262" alt="screen shot 2018-03-15 at 3 43 04 pm" src="https://user-images.githubusercontent.com/12614345/37494768-9299b388-2867-11e8-9431-3d6b18b45a3a.png">

5. Notice that the address is now verified
<img width="304" alt="screen shot 2018-03-15 at 3 43 21 pm" src="https://user-images.githubusercontent.com/12614345/37494786-9e7f6422-2867-11e8-9a47-eceb62a8d939.png">

For now, I am getting around this issue by disabling the autoverify option, but will this bug be fixed?

**Comment by camiblanch** [comment]
Currently the plugin assumes an empty form when initialized. You need to notify it of changes to the form. In the case of pre-filling a form I recommend using the jQuery `.change()` function since the plugin is set up to listen on that event. [Here's an example](https://jsfiddle.net/smartystreets/qzL3cvbu/) of how this works. Please contact our support team if you have additional questions.

**Comment by eveshumwork** [comment]
@camiblanch thanks for the quick response! Would it be possible to update the documentation to include this assumption that the plugin makes? I wasn't aware of this assumption!

Cheers,
Eve

**Comment by camiblanch** [comment]
Yes that's a great idea! I'll add that to my tasks and I'll let you know here when it's added to the documentation. I think we'll add it to the [troubleshooting section](https://smartystreets.com/docs/plugins/website/troubleshooting)

**Comment by camiblanch** [comment]
@eveshumwork We've added this to the troubleshooting page [here](https://smartystreets.com/docs/plugins/website/troubleshooting#pre-filled). Thanks again for the suggestion!
