### ISSUE TITLE
Malformed Canadian address validation

### ISSUE THREAD

**Issue by sebito91** [smartystreets/jquery.liveaddress#68]
I'm noticing with the jquery 5.1 plugin that the validated postal code is getting appending to Line1 of the address. If we try on the site with the test plugin you can see this in action:

https://smartystreets.com/docs/plugins/website/examples

200 Lonsdale Rd
Toronto, On M2H1G6
Canada

<img width="790" alt="canada" src="https://user-images.githubusercontent.com/3159454/37855230-af86b55a-2ec4-11e8-8786-dea6c6e0eea8.png">

**Comment by camiblanch** [comment]
This should be fixed now. Look for version 5.1.7 of the plugin. You shouldn't need to update your script reference at all. Sorry about that! I accidentally introduced this bug in a commit I did earlier today. Everything should be good to go now
