### ISSUE TITLE
popup position

### ISSUE THREAD

**Issue by patackett** [smartystreets/jquery.liveaddress#70]
I have a page that gathers information using tabs, with address data being on one tab and other information being gathered on other tabs.  The plugin works fine when the address tab is active, but if a user submits the form on another tab, the popup for not enough input is displayed.  However, it is displayed off the page and the user must scroll to see it.  How can I control the position of the popup?

**Comment by camiblanch** [comment]
The plugin needs to be notified that the address form is no longer being displayed. You will want to utilize the [activate](https://smartystreets.com/docs/plugins/website/functions#activate) and [deactivate](https://smartystreets.com/docs/plugins/website/functions) functions.

When the address form is visible, call `.activate()` and pass the `addressID` that correlates with your address in that form. You will also want to call `$(window).resize()` to ensure that the plugin positions correctly. The `addressID` is set in the address map. See more information on that [here](https://smartystreets.com/docs/plugins/website/functions#ID).

When the address form becomes hidden, call `.deactivate()` and pass the `addressID` that correlates with your address in that form.

[Here is an example](https://jsfiddle.net/smartystreets/mnh18fx1/) of how to do this properly, and [here is an example](https://jsfiddle.net/smartystreets/rybo6zqf/) of how to do it improperly for comparison.

Does that help?

**Comment by patackett** [comment]
Yes, that worked great.  Now, I see another issue.  I am using autocomplete and when I start typing an address, I go until the address I am looking for appears in the list and then I select it.  The plugin then fills out the appropriate address, city, state, and zip fields.  This is what I store in my database.  When I load a page to allow a user to change their address, the plugin will not verify the data that was previously saved.  It throws up the not enough input popup and if you choose to use the data it works fine. If you go back, you must start the process over of typing in the address and letting the plugin generate the autocomplete list so you can select it and get the address verified.  I somehow feel like this is a bug in the plugin but maybe I am missing something.  Any help would be greatly appreciated.  Thanks!

**Comment by camiblanch** [comment]
Excellent question! Unfortunately the plugin can only handle pre filled address forms in a very specific way. We have a [FAQ](https://smartystreets.com/docs/plugins/website/troubleshooting#pre-filled) that addresses this. It's due to how the plugin is designed to work in most use cases, but doesn't work perfectly in every use case.

**Comment by patackett** [comment]
Thanks for your help. I looked at the FAQ and made the code changes and it worked.  Thanks again!
