### ISSUE TITLE
Config Suggestions URL

### ISSUE THREAD

**Issue by ktwalrus** [smartystreets/jquery.liveaddress#71]
This plugin makes AJAX requests to 3 possible endpoints, by default:

1. https://us-street.api.smartystreets.com/street-address
2. https://international-street.api.smartystreets.com/verify
3. https://us-autocomplete.api.smartystreets.com/suggest

Endpoints #1 and #2 can be overridden using the **requestUrlUS** and **requestUrlInternational** configuration settings.

Please add a configuration setting for #3.

I want all AJAX requests to go to my server to avoid any cross-domain HTTP requests. I also want to use this plugin to implement Autocomplete for Places (in addition to Streets) by returning place names where this plugin expects freeform street addresses.

I'm integrating this plugin into my installation of Invision Community Suite and Invision's JS framework currently adds the header "X-Requested-With" to all AJAX requests. This causes this plugin's HTTP requests to be rejected due to the unexpected header. If this plugin avoided all cross-domain HTTP requests and I proxied the requests server-side, I would avoid this problem. I have filed a bug report with Invision over the extra header and requested that SmartyStreet's endpoints accept this header (as a workaround).

So, I am making this request for 3 reasons:

1. Workaround Invision bug
2. Eliminate extra CORS pre-flight requests (for increased client-side performance)
3. Use this plugin to implement autocomplete for place name fields on my website

**Comment by cbuchert** [comment]
Hey, @ktwalrus. Not sure how this fell through the cracks. I have a branch that I'll be making a pull request with that will add a config option for setting the URL for the Autocomplete API. I'll keep you posted as we determine how to address this. Please keep me posted if this is still relevant.

**Comment by cbuchert** [comment]
This plugin has been deprecated, so there will be no continued development on the project. If you're looking for a more flexible JavaScript solution for integration with SmartyStreets APIs, check out the [SmartyStreets JavaScript SDK](https://github.com/smartystreets/smartystreets-javascript-sdk).
