### ISSUE TITLE
Change waitForStreet lang

### ISSUE THREAD

**Issue by ktwalrus** [smartystreets/jquery.liveaddress#72]
I want to change the waitForStreet message to something more appropriate for my site.

Currently, it shows:
![filtered-suggestions](https://user-images.githubusercontent.com/1620132/43370797-aa0dde3e-9353-11e8-8ea3-1747c32b6d92.png)

If you don't want to implement a new config setting, at least, change the message back to "_Type more for address suggestions_".

The user doesn't know that I have applied a cityFilter to the fields so the word "filtered" might be confusing.

Also, I may need to translate this to the user's language, in the future. 

Note that I have hidden the .smarty-tag so hard-coded English strings won't show to the user.

**Comment by camiblanch** [comment]
@ktwalrus The solution I could see us implementing to solve this problem would be a configuration option to set the message like many other messages we have in the plugin. Would that solve the issue for you?

**Comment by ktwalrus** [comment]
Yes. Config setting would solve my issue.

**Comment by cbuchert** [comment]
@ktwalrus I have a branch (you can try it out [here](https://github.com/smartystreets/jquery.liveaddress/tree/chris/more-input-required-message)) that implements this. We'll review it and keep you posted. Thanks for the suggestion!

**Comment by cbuchert** [comment]
This plugin has been deprecated, so there will be no continued development on the project. If you're looking for a more flexible JavaScript solution for integration with SmartyStreets APIs, check out the [SmartyStreets JavaScript SDK](https://github.com/smartystreets/smartystreets-javascript-sdk).
