### ISSUE TITLE
autocomplete attribute overwritten

### ISSUE THREAD

**Issue by matthewhively** [smartystreets/jquery.liveaddress#77]
Hi,
We're trying to use smartystreets to verify addresses on an account administration page.
We also have account user_name and password fields on this page.
As per spec we want to have `autocomplete="new-password"`  set on the password field so that it isn't automatically filled in by the browser. But smartystreets overwrites that attribute, thus breaking that functionality.
Could smartystreets be modified so that either
A) it skips input `type=password` fields
B) it only modifies the autocomplete attribute for the inputs designated (either within addresses config, or in a new config option - default to the entire form)

Thanks

**Comment by camiblanch** [comment]
This is related to https://github.com/smartystreets/jquery.liveaddress/pull/73

**Comment by camiblanch** [comment]
This fix has been published in version 5.1.24
