### ISSUE TITLE
jQuery.Deferred exception

### ISSUE THREAD

**Issue by jayonsoftware** [smartystreets/jquery.liveaddress#78]
Our implementation of SmartyStreet stoped working today and we are getting this error. Any thoughts on what is gong on ?

`jQuery.Deferred exception: '#AddressDemo:j_id3:j_id4:editContactSection:street1' is not a valid selector disableBrowserAutofill@https://d79i1fxsrar4t.cloudfront.net/jquery.liveaddress/5.1/jquery.liveaddress.js:1237:17
UI/this.mapFields@https://d79i1fxsrar4t.cloudfront.net/jquery.liveaddress/5.1/jquery.liveaddress.js:1353:7
doMap@https://d79i1fxsrar4t.cloudfront.net/jquery.liveaddress/5.1/jquery.liveaddress.js:393:14
mapFields@https://d79i1fxsrar4t.cloudfront.net/jquery.liveaddress/5.1/jquery.liveaddress.js:398:6
$.fn.LiveAddress@https://d79i1fxsrar4t.cloudfront.net/jquery.liveaddress/5.1/jquery.liveaddress.js:490:4
$.LiveAddress@https://d79i1fxsrar4t.cloudfront.net/jquery.liveaddress/5.1/jquery.liveaddress.js:67:29
@https://flagstar--jay--c.cs11.visual.force.com/apex/AddressDemo:58:22
mightThrow@https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.js:3534:21
resolve/</process<@https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.js:3602:12`

**Comment by camiblanch** [comment]
I see. This was due to one of our recent changes. It uses the browser query selector in one line instead of just using the jQuery selector method. I will push a fix out for this real quick. Thanks for catching this and sorry it caused you some trouble.

**Comment by jayonsoftware** [comment]
Getting the following error

`Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: j_id3
    at Function.Sizzle.error (jquery.js:1541)
    at PSEUDO (jquery.js:1888)
    at matcherFromTokens (jquery.js:2437)
    at Sizzle.compile (jquery.js:2591)
    at Sizzle.select (jquery.js:2677)
    at Function.Sizzle [as find] (jquery.js:845)
    at jQuery.fn.init.find (jquery.js:2873)
    at new jQuery.fn.init (jquery.js:2983)
    at jQuery (jquery.js:139)
    at disableBrowserAutofill (jquery.liveaddress.js:1237)`

Here is the JS code we have

`   addresses: [{
                    address1: '#AddressDemo\\:j_id3\\:j_id4\\:editContactSection\\:street1',
                    locality: "#AddressDemo\\:j_id3\\:j_id4\\:editContactSection\\:city",
                    administrative_area: "#AddressDemo\\:j_id3\\:j_id4\\:editContactSection\\:state",
                    postal_code: "#AddressDemo\\:j_id3\\:j_id4\\:editContactSection\\:zip",
                    country: "#AddressDemo\\:j_id3\\:j_id4\\:editContactSection\\:country"
                }]`

**Comment by jayonsoftware** [comment]
The following also fails

`           addresses: [{

                    address1: jQuery("[id*='addressStreetOne']"),

                    locality: jQuery("[id*='addressCityOne']"),

                    administrative_area: jQuery("[id*='addressStateOne']"),

                    postal_code: jQuery("[id*='addressZipOne']")

                }]`

**Comment by camiblanch** [comment]
Alright, let's try again. Just published a better fix in 5.1.26

Are you still getting errors?

**Comment by jayonsoftware** [comment]
Its working ....Thanks for the quick turnaround
