### ISSUE TITLE
Strange Error, every address input is coming as false. 

### ISSUE THREAD

**Issue by jayonsoftware** [smartystreets/jquery.liveaddress#79]
This works

https://us-street.api.smartystreets.com/street-address?auth-id=14399859584338631&agent=smartystreets%20(plugin%3Awebsite%405.1.26)&street=4142%20Cherrywood%20Dr&city=Troy&state=MI&match=&candidates=3

This does not

https://us-street.api.smartystreets.com/street-address?auth-id=14399859584338631&agent=smartystreets%20(plugin%3Awebsite%405.1.26)&street=4142%20Cherrywood%20Dr&city=Troy&state=Michigan&match=&candidates=3

Was some thing got changed on the backend that is ignoring state named "Michigan" and only taking "MI". All this worked well until last night :-)

Jay

**Comment by cbuchert** [comment]
Alright, @jayonsoftware. The issue was a back-end issue on the API. I've been assured it's been resolved. Keep us posted if you continue to have trouble.
