### ISSUE TITLE
Code that adds "Pick a state" checks drop down options incorrectly 

### ISSUE THREAD

**Issue by thavelick** [smartystreets/jquery.liveaddress#81]
LiveAddress contains some code that adds a "Pick a state" to state dropdowns that do not already have a default choice.  This is done in the function `addDefaultToStateDropdown()`.  However, the expression used there, `dom.getElementsByTagName("option")[0].text.toUpperCase()` always grabs the *first* dropdown on the page whether or not that dropdown is the state dropdown specific for that page.

Thus, if you have a page that a non-state dropdown above the state dropdown, "Pick a state" will not get added to either field.  This code should probably be changed such that it looks at the state field specified by the `address.administrative_area` specified in the configuration.

**Comment by cbuchert** [comment]
Great suggestion, @thavelick. Will you put together a pull request and I'll review it? We'd love to give you contributor credit.

**Comment by cbuchert** [comment]
This plugin has been deprecated, so there will be no continued development on the project. If you're looking for a more flexible JavaScript solution for integration with SmartyStreets APIs, check out the [SmartyStreets JavaScript SDK](https://github.com/smartystreets/smartystreets-javascript-sdk).
