### ISSUE TITLE
AddressChanged can be called when validation is in progress

### ISSUE THREAD

**Issue by summersab** [smartystreets/jquery.liveaddress#82]
This may be something to take care of once @camiblanch is back from maternity leave, but I ran into some excitement when integrating with FoxyCart. Due to the way FoxyCart's templating system works, certain blocks of the DOM are completely re-rendered on a regular basis as different events fire. This made getting SmartyStreets to behave particularly difficult, and I was able to uncover a potential flaw.

In short, after SS' VerificationInvoked event fires, AddressChanged events aren't blocked from firing, and the data.address object can be modified in the midst of an ongoing verification (in my case, RIGHT before the ajax call). While this may seem like a rare edge-case, it took me several days to figure out why Foxy and Smarty just wouldn't play well together, and this wound up being the exact reason.

I suggest that AddressChanged events be blocked from executing after any VerificationInvoked event fires much in the same way that a VerificationInvoked event currently blocks duplicate VerificationInvoked events from firing once one is already in flight. I'm not sure if this change would be substantial enough to cause impact to other integrations out there - I can't imagine that any integration is taking _advantage_ of such a feature, after all. Still, though . . . tread carefully. :-)

**Comment by cbuchert** [comment]
@summersab, I think you're right re: concern about introducing breaking changes. I think in this case that discretion is the better part of valor. :| Will you put together a pull request with the changes? We'll review it and make a more final call.

**Comment by summersab** [comment]
Oy - I can't claim to be a developer, really. While I have a degree in CS and CAN code, I'm more of the sys admin type, and I've never cloned a repo or made a pull request. I can certainly try, though, but it might be after Black Friday . . .

**Comment by cbuchert** [comment]
Okay. I'll look into this some more and put together a pull request for it. I'll keep you posted.

**Comment by cbuchert** [comment]
This plugin has been deprecated, so there will be no continued development on the project. If you're looking for a more flexible JavaScript solution for integration with SmartyStreets APIs, check out the [SmartyStreets JavaScript SDK](https://github.com/smartystreets/smartystreets-javascript-sdk).
